---
title: "AM14_GA1"
author: "Group 10"
date: "1/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries 

```{r, Load libraries}
library(ggplot2)  
library(dplyr)
library(tidyverse)
library(readxl)
library(lubridate)
library(skimr)
library(moments)
library(e1071) 
```

## Question 1

Load the monthly stock data. We will also load the daily stock data, which we'll need later in the assignment.

```{r, Load the data}
monthly_data <- read_excel("PS1_Monthly.xlsx") %>%
  janitor::clean_names()
daily_data <- read_excel("PS1_Daily.xlsx") %>%
  janitor::clean_names()

skimr::skim(monthly_data)
skimr::skim(daily_data)
```


## Question 2

Now, returns bla bla bla 

Also - upon inspection, the dates are not in the right format and need to be transformed. 

```{r, Question 2}

question2 <- c('MSFT', 'GE')

monthly_data <- monthly_data %>%
  mutate(date = ymd(date)) %>%
  filter(ticker %in% question2) %>%
  mutate(rti = (ret/lag(ret)) - 1,
         rti_sp = (sprtrn/lag(sprtrn)) - 1,
         rtix = (retx/lag(retx)) - 1) 

ggplot(monthly_data, aes(x=date, y=rti, group=ticker, color=ticker)) +
    geom_line() +
  theme_minimal()

ggplot(monthly_data, aes(x=date, y=rtix, group=ticker, color=ticker)) +
    geom_line() +
  theme_minimal()
```

## Question 3

```{r}
# mutate LRET variables
monthly_data <- monthly_data %>%
                mutate(lret = log(ret)) 

# calculate mean, variance, skewness, and kurtosis of the normal returns
monthly_data %>% 
  summarise(mean_ret = mean(ret),
            var_ret = var(ret),
            skew_ret = skewness(ret),
            kurt_ret = kurtosis(ret))
# calculate mean, variance, skewness, and kurtosis of the log returns
monthly_data %>% 
  na.omit() %>%
  summarise(mean_lret = mean(lret),
            var_lret = var(lret),
            skew_lret = skewness(lret),
            kurt_lret = kurtosis(lret))

# Plot the normal against the log returns for MSFT
monthly_data %>%
  mutate(date = ymd(date)) %>%
  filter(ticker == "MSFT") %>%
  na.omit() %>%
  ggplot(aes(x=ret, y=lret)) +
    geom_line() +
    theme_minimal()
```

```{r}
#daily_clean <- daily_data %>%
#mutate(date = ymd(date)) 
```

